name: storage_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  local_auth: ^2.1.0
  qr_code_scanner: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/storage.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/storage.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/instruction/
    - google_fonts/
