// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQPCz4mNyq2rAxaFhH7txyLgrsNo6eyk',
    appId: '1:717821370979:android:9df106829e4ecee111ce56',
    messagingSenderId: '717821370979',
    projectId: 'storage-app-8c587',
    storageBucket: 'storage-app-8c587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6XnabT5r3FHOvBQmc1ut4b6f4Sme0Dk',
    appId: '1:717821370979:ios:2291c26203e54b4911ce56',
    messagingSenderId: '717821370979',
    projectId: 'storage-app-8c587',
    storageBucket: 'storage-app-8c587.appspot.com',
    androidClientId: '717821370979-l8et616u0u532afd24fteu7tkp74l497.apps.googleusercontent.com',
    iosClientId: '717821370979-3rqc8gnsn77p87oljhliif4kg56d0dmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageApp',
  );
}
